name: Run Shell Script

on: [push]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show permissions
        run: ls -l
        
      - name: Give permission
        run: chmod +x test.sh

      - name: Run script
        run: ./test.sh
